### PR TITLE
Fix empty request body on retries with compression enabled

### LINKED ISSUE #541: [BUG] Error http: ContentLength=401 with Body length 0
### What is the bug?
I'm getting lots of these errors when indexing documents into a data stream:
`http: ContentLength=401 with Body length 0`

### How can one reproduce the bug?
Here's my code:
```go
func (logger *MyLogger) SendLogEvent(event *MyLogEvent) error {
	// Marshal the struct
	s, err := json.Marshal(event)
	if err != nil {
		return WrapError("failed to marshal log event", err)
	}
	// Do the request
	req, err := opensearchapi.IndexReq{
		Index: logger.logsIndexName,
		Body: bytes.NewReader(s),
	}.GetRequest()
	if err != nil {
		return WrapError("failed to create OpenSearch index request", err)
	}
	resp, err := logger.client.Perform(req)
	// Make sure to close the body so the connection can be reused
	if resp != nil && resp.Body != nil {
		defer resp.Body.Close()
	}
	if resp == nil {
		return err
	}
	if err != nil || resp.StatusCode != 201 {
		// Log the error
		return errors.New("failed to log event, statuscode " + resp.Status)
	}
	// Still read the body so the connection can be reused
	io.Copy(io.Discard, resp.Body)
	// Success
	return nil
}
```

### What is the expected behavior?
No error.

### What is your host/environment?
Debian 12 and Linux Mint 21.3
opensearch-go v4.0.0

### PR DESCRIPTION
**Pull request by merlinz01**
### Description
Make the transport use a new reader for each retry when gzip compression is enabled.
Also be more explicit about doing so for non-compressed requests.
Test included.

### Issues Resolved
Closes #541.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by dblock — APPROVED** [review]

File: opensearchtransport/opensearchtransport.go [hunk 1]
```diff
@@ -258,8 +260,9 @@ func (c *Client) Perform(req *http.Request) (*http.Response, error) {
 				//nolint:errcheck // ignored as this is only for logging
 				buf.ReadFrom(req.Body)
 				req.GetBody = func() (io.ReadCloser, error) {
-					r := buf
-					return io.NopCloser(&r), nil
+					// Return a new reader each time
+					reader := bytes.NewReader(buf.Bytes())
+					return io.NopCloser(reader), nil
```
Comment (dblock) [inline opensearchtransport/opensearchtransport.go:265]: Are we missing a test for this path?

Comment (merlinz01) [reply opensearchtransport/opensearchtransport.go:265]: There is an existing test for the reader reset behavior on non-compressed request body:
https://github.com/opensearch-project/opensearch-go/blob/41fd58f31b62a0d1edb6f7e506640c79b6a6017f/opensearchtransport/opensearchtransport_internal_test.go#L655-L690

Comment (dblock) [reply opensearchtransport/opensearchtransport.go:265]: But that test is passing without your code change?

Comment (merlinz01) [reply opensearchtransport/opensearchtransport.go:265]: Notice there are two test cases now, one for retries without compression and one (from this PR) for retries with compression.

The code for uncompressed works correctly and passes the relevant test, both with and without my changes.
The old code does a copy of the unread `buf` into `r` so that `buf` as referenced from the closure remains unread. With my changes, it is a bit more obvious what is being done but it functions the same.
So no, if you revert those two lines, no tests will fail. The bug is only in the code for compressed.

The code for uncompressed was from https://github.com/opensearch-project/opensearch-go/commit/fb7bdd15c1e392734922bece65d3c203a4aefb95 and code for compressed was from https://github.com/opensearch-project/opensearch-go/commit/8cf8bd25e2b7f6fefe3b946f20555272bf8c3c47 but the bug was introduced in https://github.com/opensearch-project/opensearch-go/commit/7ea16f7de5fa5d45a0930619868466f5fc430ee2 with pooled gzip compressors.

Comment (dblock) [reply opensearchtransport/opensearchtransport.go:265]: Understood! Thank you for being patient with me.

**Comment by dblock** [comment]
@merlinz01 Looks like you need to fix DCO (`git commit -s --amend`), please?

File: CHANGELOG.md [hunk 2]
```diff
@@ -17,6 +17,8 @@ Inspired from [Keep a Changelog](https://keepachangelog.com/en/1.0.0/)
 
 ### Fixed
 
+- Fixes empty request body on retry with compression enabled. ([#543](https://github.com/opensearch-project/opensearch-go/pull/543))
```
Comment (dblock) [inline CHANGELOG.md:20]: Nit: remove period at the end of the sentence, other lines don't have it.

Comment (merlinz01) [reply CHANGELOG.md]: Done.

**Comment by merlinz01** [comment]
DCO successful.

**Review by dblock — APPROVED** [review]

**Comment by dblock** [comment]
Thanks! We have lots of other things in https://github.com/opensearch-project/opensearch-go/issues if you have free time :)
